language: cpp

matrix:
  include:
    - name: "linux_x64"
      os: linux
      sudo: required
      env: 
        - DOCKER_IMAGE=pmeira/manylinux_wheel_cmake_fpc
        - DSS_CAPI_TAG=0.10.3a4
        - LINUX_X64=1
        - CONDA_SUBDIR=linux-64
      services:
        - docker
      install:
        - docker pull $DOCKER_IMAGE
      script: 
        - export TRAVIS_TAG_DSS_PYTHON=$TRAVIS_TAG
        - export TRAVIS_TAG=
        - cd ..
        - wget https://github.com/dss-extensions/dss_capi/releases/download/${DSS_CAPI_TAG}/dss_capi_${DSS_CAPI_TAG}_linux_x64.tar.gz -q -O dss_capi.tar.gz
        - tar zxf dss_capi.tar.gz
        - mkdir artifacts
        - mkdir artifacts/linux-64
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE bash /io/dss_python/ci/build_linux.sh
        - export DSS_CAPI_PATH=`pwd`/dss_capi
        - bash dss_python/ci/build_linux_conda.sh
        - ls -lR artifacts
        
    - name: "linux_x86"
      os: linux
      sudo: required
      env: 
        - DOCKER_IMAGE=pmeira/manylinux_wheel_cmake_fpc_i686
        - DSS_CAPI_TAG=0.10.3a4
        - CONDA_SUBDIR=linux-32
      services:
        - docker
      install:
        - docker pull $DOCKER_IMAGE
      script: 
        - export TRAVIS_TAG_DSS_PYTHON=$TRAVIS_TAG
        - export TRAVIS_TAG=
        - cd ..
        - wget https://github.com/dss-extensions/dss_capi/releases/download/${DSS_CAPI_TAG}/dss_capi_${DSS_CAPI_TAG}_linux_x86.tar.gz -q -O dss_capi.tar.gz
        - tar zxf dss_capi.tar.gz
        - mkdir artifacts
        - mkdir artifacts/linux-32
        - docker run --rm -v `pwd`:/io $DOCKER_IMAGE bash /io/dss_python/ci/build_linux.sh
        - ls -lR artifacts

    - name: "osx_x64"
      os: osx
      env: 
        - DSS_CAPI_TAG=0.10.3a4
      script: 
        - export TRAVIS_TAG_DSS_PYTHON=$TRAVIS_TAG
        - export TRAVIS_TAG=
        - cd ..
        - wget https://github.com/dss-extensions/dss_capi/releases/download/${DSS_CAPI_TAG}/dss_capi_${DSS_CAPI_TAG}_darwin_x64.tar.gz -q -O dss_capi.tar.gz
        - tar zxf dss_capi.tar.gz
        - export DSS_CAPI_PATH=`pwd`/dss_capi
        - cd dss_python
        - bash ci/build_osx.sh
        - ls -lR ../artifacts

    # - name: "windows_x64"
      # os: windows
      # script: 
        # - git clone https://github.com/dss-extensions/electricdss-src ../electricdss-src
        # - git clone https://github.com/dss-extensions/dss_capi ../dss_capi
        # - bash ci/build_windows.sh
        # - ls -lR ../artifacts

# deploy:
  # provider: releases
  # api_key:
    # secure: gteKiE+9iIOJm4/zvsF1kJolU5lFTwVvF7HGW6UZ/aGymcjueE257EXGHc+isOkXyFd8qdyUlCBB9O70pFKMPIB4R5Nn+T59TuiyMWKya42ToyKbJDYSXs5g1tadHOA1NEJKBAq8etvIbTtS7QxoLa+Nl/bqNCfNI+g85zUyyraiyAuSx3LaN+98QXAckFNysripuGIYzN9T6XKg1bpQB2htJNoq/e9xZM7WwANp0ce1Kjd7kU9iHX0+BEqeLTZNuJT+2FGHfl9hKtek5V23ZZre419Azo1HP3voK+mCzqOobVrUUKHK2Pc/npBs+4bQhCr7tClWm/ixQmOC66WBUhzVHrnMZASd5GwS5H3dDUcG6sv8vstohTaw+EGKtXWVxO6atCGCgHL9QOEwBnKv85BPLJq8aS3fE2I1M17J0+OjNp7bN3ldCnTPZOs7+5DwbhMiMhFc9iOVxmjXkoBVgsBzODcH6iXOOZBDHcO5CuJzhJq64sDKsQ/Nm5qEV64QwqtZigbktb3OFbqAu7aZc4FUYmyGt4OnmJVK0l3d0EBJORVmiwtedw0KFSOwoBXQbEN7hWfaqlCMD/8tbxIyEtGFDah3F+Jte56ShMZuMd2wOQsvifsV2DejWagdWHi9ZZJQVFeqlYRfc9rHj8F0fUoqapWbk2folkWi503g2Bc=
  # file_glob: true
  # file: ../artifacts/*
  # on:
    # repo: dss-extensions/dss_python
    # tags: true
    